[package]
name = "three"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age-threshold = { path = "../age-threshold" }
clap = "4.5.1"
